sudo: required
services:
  - docker

before_install:
  - docker build -t prashant/docker-react -f Dockerfile.dev .

script:
  - docker run prashant/docker-react npm run test -- --coverage

  deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-ap-south-1-140640375467"
    bucket_path: "docker"
    on:
      branch: master
    access_key_id:
      secure: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"
      